export const defaultContentTypes =  [
	'country',
	'currency',
	'fulfillment-provider',
	'image',
	'money-amount',
	'payment-provider',
	'product',
	'product-category',
	'product-collection',
	'product-metafield',
	'product-option',
	'product-option-value',
	'product-tag',
	'product-type',
	'product-variant',
	'region',
	'shipping-option',
	'shipping-option-requirement',
	'shipping-profile',
	'store',
] as const;
