name: Docker Image CI Development

on:
  push:
    branches: [ "master" , 'release/**', "development"]
  pull_request:
    branches: [ "master","development" ]

jobs:

  build:
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: List files 
      run: ls
      working-directory: ./packages/medusa-strapi
    - name: Build the Docker image
      run: docker build . -t sgf-strapi --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID  --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_DEFAULT_REGION="ap-south-1"  --no-cache
      working-directory: ./packages/medusa-strapi
