name: SGF-strapi
on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [16.x]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-verion }}

      - name: 'yarn install'
        working-directory: ./
        run: yarn install --frozen-lockfile

      - name: 'yarn build'
        working-directory: ./
        run: yarn run build 

      - name: 'run unit tests'
        working-directory: ./
        run: yarn run test