name: medusa-strapi integration
on:
  push:
    branches:
      - master
      - 'release/**'
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  integration-test:
    env:
      NODE_ENV: 'test'
      APP_KEYS: ${{secrets.APP_KEYS}}
      TRANSFER_TOKEN: ${{secrets.TRANSFER_TOKEN}}
      API_TOKEN_SALT: ${{secrets.API_TOKEN_SALT}}
      ADMIN_JWT_SECRET: ${{secrets.ADMIN_JWT_SECRET}}
      MEDUSA_STRAPI_SECRET: ${{secrets.MEDUSA_STRAPI_SECRET}}
## Admin Settings
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [16.x]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-verion }}

      - name: 'yarn install'
        working-directory: ./
        run: yarn install --frozen-lockfile

      - name: 'yarn build '
        working-directory: ./
        run: yarn run build 

      - name: 'setup up strapi test environment'
        working-directory: ./packages/medusa-strapi
        run: yarn run start &
      - name: wait for server to start
        run: sleep 60s
        shell: bash
      - name: 'run medusa plugin strapi unit tests'
        working-directory: ./packages/medusa-plugin-strapi-ts
        run: yarn run test
